### ISSUE TITLE
How to run this nlp Parser

### ISSUE THREAD

**Issue by Mohit21k** [hristo-vrigazov/Natural-language-parser#2]
Hi,
Can you please help me out how to run this nlp parser.

**Comment by hristo-vrigazov** [comment]
Hi @Mohit21k , thanks for asking. You can run the example by running the `test.py` file. It outputs file similar to this one: https://github.com/hristo-vrigazov/Natural-language-parser/blob/master/code/test.conll By default it uses an example danish data. If you are not familiar with the format, you can read more about it here: http://universaldependencies.org/format.html

Note: This was developed as part of the Coursera's course "Introduction to Natural Language Processing" https://www.coursera.org/learn/natural-language-processing and I do not recommend using it in production, as the results were not amazing, I barely passed the course. But it was fun as a learning experience :)

**Comment by hristo-vrigazov** [comment]
As this is not a project I plan to maintain, I will close the issue, to not clutter my backlog, but feel free to ask more questions.

**Comment by Mohit21k** [comment]
Thanks @hristo-vrigazov for your response
